// 🔥 Keep ONLY this one block
export const products = [
  {
    _id: 1,
    name: "Vintage Pocket Watch",
    price: 2500,
    category: "Watches",
    image: "https://images.pexels.com/photos/277319/pexels-photo-277319.jpeg",
    description: "Classic vintage pocket watch with intricate metalwork case.",
  },
  {
    _id: 2,
    name: "Royal Gold Pocket Watch",
    price: 3800,
    category: "Watches",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQENlx1LCsTbf3vKQQDG3lNBHFt6tinamDDzw&s",
    description: "Royal golden finish with premium hand-engraving.",
  },
  {
    _id: 3,
    name: "Antique Steel Chain Watch",
    price: 2900,
    category: "Watches",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKEjEBNHyssXQPDnKwc4o9tjnJujsnMqU_CQ&s",
    description: "Steel pocket watch with durable chain and elegant dial.",
  },
  {
    _id: 4,
    name: "Antique Table Clock",
    price: 3200,
    category: "Clocks",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTo6K7ZEzNXbZIfOKPP59yZXB-8IC5UDWypxg&s",
    description: "Beautiful antique wooden table clock for your living room.",
  },
  {
    _id: 5,
    name: "Retro Bronze Clock",
    price: 4000,
    category: "Clocks",
    image: "https://m.media-amazon.com/images/I/61d75s0exZL.jpg",
    description: "Pure bronze old classic desk clock with carved designs.",
  },
  {
    _id: 6,
    name: "Vintage Wall Clock",
    price: 4500,
    category: "Clocks",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRtqDSvewDHiZjjl4h35mYyxFbcmggw8dIpg&s",
    description: "Historic wall clock from European castle era.",
  },
  {
    _id: 7,
    name: "Retro Camera",
    price: 4500,
    category: "Cameras",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzeT2k7gZ5VnAxyCDyGrGSbHrNvhOD6PK-5g&s",
    description: "Functional retro camera, perfect for collectors and decor.",
  },
  {
    _id: 8,
    name: "Classic 90s Camera",
    price: 4990,
    category: "Cameras",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUBtTL-fLnZ7uxiPJcFCLn1qSVor-LXmM3Ig&s",
    description: "Film camera with premium shutter functionality.",
  },
  {
    _id: 9,
    name: "Black Retro Camera",
    price: 4200,
    category: "Cameras",
    image: "https://images.pexels.com/photos/122400/pexels-photo-122400.jpeg",
    description: "Durable camera used during 1980 classic film era.",
  },
  {
    _id:10,
    name: "Vintage Photo Camera",
    price: 5200,
    category: "Cameras",
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQFTGLm8fsee_K6rhyHw4zz6az1d5XxR3TUGJzMIklFitlfnAheAst0BqsaZiqE7Mk0q0dmdNJGCBbnIz4dq1bqp3mWw_I9GlHKYjm-C33vPp-BBmv96TbI",
    description: "Legendary DSLR look with analog filming system.",
  },
  {
    _id: 11,
    name: "Antique Metal Camera",
    price: 6200,
    category: "Cameras",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoZkDnTBaQVqRhuSqlz_LUBzYuzD2XTnUYlg&s",
    description: "Solid old-era camera with metallic body craftsmanship.",
  },
  {
    _id: 12,
    name: "Classic Typewriter",
    price: 3800,
    category: "Typewriters",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQjUn7NunGKPG4ewrARe1-3K0I7BMm1b6ZBA&s",
    description: "Old-school typewriter with metal keys and solid body.",
  },
  {
    _id: 13,
    name: "Retro Office Typewriter",
    price: 4500,
    category: "Typewriters",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcpzb_w0Z3YIt9U4qR4us07qH8uctVq1l-jQ&s",
    description: "Industrial-era typewriter with smooth typing mechanism.",
  },
  {
    _id: 14,
    name: "Nostalgic Vintage Typewriter",
    price: 4999,
    category: "Typewriters",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0qs7YPoys40k7FiE1LBhLtpwDW3xZ5xhF0A&s",
    description: "A collector’s dream, highly demanded in auctions.",
  },
  {
    _id: 15,
    name: "Antique Royal Typewriter",
    price: 5600,
    category: "Typewriters",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbg-EwMC0IX6E7SOF-W5e6oQMjfPNrdS68-Q&s",
    description: "Premium leather grip with cast-iron frame.",
  },
];
